### ISSUE TITLE
Create Reading Frames

### ISSUE THREAD

**Issue by SteveWLU** [wludh/huon_rails#11]
I'd like to explore creating scrolling reading frames for the individual laisse, if possible like the interface for the Shelly-Godwin archive: http://shelleygodwinarchive.org/sc/oxford/ms_abinger/c56/#/p5

In any case, it would be good to create a visually distinct area for the text.

**Comment by walshbr** [comment]
I explored this a little back in the day. Were you imagining for the notes and the text, or just the text?
