### ISSUE TITLE
updating schedule?

### ISSUE THREAD

**Issue by LZMorgan** [wludh/huon_rails#124]
Should we set a certain updating schedule, e.g., each Saturday evening, so that anything new can be brought in at that point, with errors caught, etc.?

**Comment by SteveWLU** [comment]
This is a great idea! We can post here all the edits we want to make for every Saturday evening, then I'll push all of the edits to the main site. 

I'll put a line somewhere in the About page that the site is updated Saturday evenings...

**Comment by LZMorgan** [comment]
Glad you agree!
Leslie

L. Zarker Morgan
Professor of Italian and French
Associate Chair for Student Issues
Coordinator of the Italian Language Program
Modern Languages and Literatures
http://www.loyola.edu/academics/modern-languages/faculty/morgan
