### ISSUE TITLE
Variant display

### ISSUE THREAD

**Issue by walshbr** [wludh/huon_rails#16]

**Comment by walshbr** [comment]
Can toggle on and off corr styling now.

**Comment by SteveWLU** [comment]
OMG BRANDON. Geeez. You're killing this.
(Is this an issue to keep open?)

**Comment by walshbr** [comment]
Yeah I wasn't sure if that was what you had in mind for displaying variants. For one, it's not interacting with sic or expan tags at all now. And the corr display is just turning the text red, so would be good to have input on what you wanted. So just let me know if this is what you in mind!
