### ISSUE TITLE
Distinguish notes from variants

### ISSUE THREAD

**Issue by walshbr** [wludh/huon_rails#18]

**Comment by SteveWLU** [comment]
What does this mean, Brandon?

**Comment by walshbr** [comment]
When we met and were writing on the board, you said that you wanted to distinguish notes that were annotations from notes that were describing variants in some way. At least that's how I remember it. It's easy enough for me to just add a little subtitle in the side panel indicating what type of note we were discussing if that's what you had in mind.

**Comment by walshbr** [comment]
I will need a way to map the note types to some text describing them or something like that. I can just pull from the notesStmt, which seems to be the best option, but right now the descriptions of note types are not quite ready for giving out to the public. Something like "Note of type X, which are 'notes that reference secondary sources." or something like that?
