### ISSUE TITLE
<pb> replaced with <milestone> and new attributes

### ISSUE THREAD

**Issue by SteveWLU** [wludh/huon_rails#64]
Hi, Brandon, 

I've replaced the tags <pb n="f.114v"/> with <milestone n="114v" unit="fol.">.

This I think will make it easier to track and display folio numbers, and would be more specific to manuscript than print. If you think this is not a good idea, let me know...
I've been looking over the TEI for the Piers Plowman project and they use this system.

**Comment by walshbr** [comment]
https://www.youtube.com/watch?v=jxpuTEOEVvQ

**Comment by walshbr** [comment]
What are we replacing them with? I'll just need to update the css and the parser.

**Comment by SteveWLU** [comment]
ooops... the tag in the original issue message disappeared. I've replaced pb with milestone.

**Comment by SteveWLU** [comment]
hahaha!  

BRANDON! I thought that was going to be a kitten video. No, it was a computer blowing up.
