### ISSUE TITLE
do the notes in the notes-tei files need note numbers?

### ISSUE THREAD

**Issue by walshbr** [wludh/huon_rails#67]
Right now the parser is just renumbering them when they get loaded in, so that Steve doesn't have to worry about renumbering everything. Could theoretically take out the n attribute then. I bring this up because I noticed that @mccormicks was starting to use ?? for the n attribute. technically it should not make a difference. Just a question of TEI praxis.

**Comment by SteveWLU** [comment]
@bmw9t @mackenziekbrooks I'm wondering too if we could take the note numbers out, or if it is best practice to have them in. In any case, I've simplified the system I'm using to identify the notes, using now the line number and the manuscript sigla, instead of the folio and the note number on the folio. This makes it easy to know where they go, etc.

**Comment by mackenziekbrooks** [comment]
The Guidelines say, "However, if notes are numbered in sequence and their numbering can be reconstructed automatically by processing software, it may well be considered unnecessary to record the note numbers." 

I think we are fine to drop note numbers if you have another system in place.

**Comment by walshbr** [comment]
Yeah - they're not numbered in sequence in the TEI itself - I'm using ruby to count and number them for the live site. They have unique xml id numbers, but that's it. It sounds like two of us are ambivalent and one wants to leave them out. So shall we just say we'll leave them out?

But I do think it is worth noting that they are numbered based on their order in the TEI file. So if you have a note for laisse IV, but put it at the end of the notes file, it could wind up having a superscript number of 90. So maybe we can say:

no numbering using n attributes
unique xml id #'s will be used instead.
But when adding new notes, they should be added relative to the notes for related line numbers? So rather than just inserting new notes in notes-xml files at the end, you'll try to fit them in where you want them to go in the numerical list. That way you won't have to renumber all the tags, and the ordering will be maintained by rails.

Does that make sense?

**Comment by SteveWLU** [comment]
Makes sense. I will keep the notes chronological as they are to appear in the edition. 
I'll get rid of the n attribute.

Thanks, guys!
