### ISSUE TITLE
Notes Statement in Header

### ISSUE THREAD

**Issue by SteveWLU** [wludh/huon_rails#71]
@mackenziekbrooks 

Hi, Mackenzie... I've included a notes statement in the header to the P edition and its notes file. I've sent a screen shot via slack. Does this look right? Is there other information that you would expect to see in this?

**Comment by mackenziekbrooks** [comment]
This looks fine to me. Notes are just a catch all for anything that doesn't have a more specific tag in the teiHeader. 

Are you just keeping track of note types for yourself, or do you plan to incorporate them into the site?

**Comment by walshbr** [comment]
Refs #18 - That was a question I had too. I think Steve wanted to use those note types in some way, but they're not being used for anything yet. If you let me know how you want them used in the interface I can adjust.

**Comment by SteveWLU** [comment]
HI guys, 

Yes, I had the idea to document the note types in the head. I sent the screenshot to Mackenzie, I'll send it to you too, Brandon, in a sec. I'm thinking that later down the road it'll be useful, but I don't have any clear ideas just yet. ..
